services:
  - type: web
    name: spring-boot-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    pullRequestPreviewsEnabled: true
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /actuator/health
    plan: free
    numInstances: 1
